org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
loomx.loom_version=1.18.0-alpha.8

mod_id=modern_f3
mod_name=Modern F3
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=me.almana
mod_authors=AlmanX21
mod_description=A modern replacement for Minecraft's debug overlay
